### PR TITLE
chore: Update Owlbot filenames

### LINKED ISSUE #78: Warning: a recent release failed
The following release PRs may have failed:

* #70 - The release job was triggered, but has not reported back success.

### PR DESCRIPTION
**Pull request by holtskinner**
Fixes #78 🦕

### CODE REVIEW

**Comment by holtskinner** [comment]
@parthea It looks like Owlbot keeps undoing the changes that are made to satisfy the linter.
It's also undoing a change I made to resolve a security vulnerability. I wonder if a change needs to be made to the core owlbot config to make these adjustments?

**Comment by holtskinner** [comment]
Made https://github.com/googleapis/synthtool/pull/1774 to update the requirements in synthtool

**Comment by holtskinner** [comment]
Made https://github.com/googleapis/synthtool/pull/1775 to fix the lint errors

**Comment by holtskinner** [comment]
Created https://github.com/googleapis/python-documentai-toolbox/pull/83 to increase some test coverage. (99% is still enforced)

**Comment by holtskinner** [comment]
Ok, with the auto-formatting working, https://github.com/googleapis/synthtool/pull/1775 isn't a blocker.

**Review by parthea — APPROVED** [review]

**Pull request merged**
